url: https://davidongo93.github.io/
# Site settings
title: Experience Showcase
email: domirandar@unal.edu.co
description: "Portfolio showcase About my career"

# Team names, titles, and social links
people:
  - name: David Orlando Miranda
    pic: 2
    position: Full stack developer 
    social:
      - title: twitter
        url: https://twitter.com/domirandar
      - title: github
        url: http://github.com/davidongo93
      - title: linkedin
        url: https://www.linkedin.com/in/domirandar

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/domirandar
  - title: github
    url: http://github.com/davidongo93
  - title: linkedin
    url: https://www.linkedin.com/in/domirandar

# Postal address (add as many lines as necessary)
address:
  - line: ----
  - line: Bogotá-Colombia-South America.

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag

# Assets
include:
  - assets
