# Site settings
title: Experience Showcase
email: domirandar@unal.edu.co
description: "Personal Site Developer"


# Team names, titles and social links
people:
  - name: David Orlando Miranda
    pic: 1
    position: Full stack developer 
    social:
      - title: twitter
        url: 
      - title: github
        url: http://github.com/davidongo93
      - title: linkedin
        url: https://www.linkedin.com/in/david-orlando-miranda-roa-7239b0264/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/DavidMiranda93
  - title: github
    url: http://github.com/davidongo93
  - title: linkedin
    url: https://www.linkedin.com/in/david-orlando-miranda-roa-7239b0264/

# Postal address (add as many lines as necessary)
address:
  - line: ----
  - line: Bogotá-Colombia-South america.

# Build settings
markdown: kramdown
permalink: pretty